services:
  # MySQL: Geograf√≠a y Deportes
  mysql_db:
    image: mysql:8.0
    container_name: trivia_mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin_password
      MYSQL_DATABASE: trivia_db
    ports:
      - "3306:3306"

  # Redis: Ciencias
  redis_db:
    image: redis:alpine
    container_name: trivia_redis
    ports:
      - "6379:6379"

  # MongoDB: Arte
  mongo_db:
    image: mongo:latest
    container_name: trivia_mongo
    ports:
      - "27017:27017"